global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      # https://docs.docker.com/desktop/networking/#i-want-to-connect-from-a-container-to-a-service-on-the-host
      - targets: ['localhost:9090']

  - job_name: 'application'
    static_configs:
      - targets: ['localhost:7001']
