version: "3"

services:
  prometheus:
    image: prom/prometheus:v2.43.1
    restart: unless-stopped
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:9.5.1
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - 8000:3000

volumes:
  prometheus_data:
  grafana_data:
